name: "secrets"
description: "set secrets"
inputs:
  global:
    description: "set global secrets"
    required: false 
    default: "false"
  dir:
    description: "set directory secrets"
    required: false 
    default: "."
runs:
  using: "node20"
  main: "app/dist/main.js"
