name: Testing github actions 
on:
  workflow_dispatch:
env:
  SRC: ${{github.workspace}}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  VAULT_ROOT_TOKEN: ${{ secrets.VAULT_ROOT_TOKEN }}
  VAULT_ADDR: ${{ secrets.VAULT_ADDR}}
jobs:
  secrets:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{env.SRC}}/actions/secrets
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v3
      - uses: ./actions/env
        name: "set environment context"
      - uses: ./actions/vault
        name: "install vault and login with inputs"
      - uses: ./actions/secrets
        name: "set global secrets"
        with:
          global: "true"
      - run: echo $GCP_PROJECT_NAME
        name: "testing global secrets"
      - uses: ./actions/secrets
        name: "set directory secrets"
        with: 
          dir: ${{ github.workspace }}/actions/secrets
      - run: echo $THE_THING
        name: "testing directory secrets"
      


      