name: Testing github actions 
on:
  workflow_dispatch:
env:
  SRC: ${{github.workspace}}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  VAULT_ROOT_TOKEN: ${{ secrets.VAULT_ROOT_TOKEN }}
  VAULT_ADDR: ${{ secrets.VAULT_ADDR}}
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v3
      - uses: ./actions/terraform
        with:
          version: "1.3.7"
      - run: terraform --help

    
