name: Testing github actions 
on:
  workflow_dispatch:
env:
  SRC: ${{github.workspace}}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  VAULT_ROOT_TOKEN: ${{ secrets.VAULT_ROOT_TOKEN }}
  VAULT_ADDR: ${{ secrets.VAULT_ADDR}}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v3
      - name: "Install utils actions"
        uses: actions/checkout@v4
        with:
          repository: ghostmind-dev/play
          ref: main
          path: actions
          sparse-checkout: play
      - run: ls -la

      # - uses: denoland/setup-deno@v1
      #   with:
      #     deno-version: canary
      # - name: "Install dependencies"
      #   run: npm install  
      #   if: ${{ github.event.inputs.LIVE != 'true'}}
      # - name: "Build"
      #   run: npm run build
      # - name: "Test dev mode"
      #   uses: ./
      #   with:
      #     dev: ${{ github.event.inputs.LOCAL }}
      # - run: run
      # - run: $HOME/run/run/bin/cmd.ts
      # - name: "Test published mode"
      #   uses: ./
      #   with:
      #     dev: false
      # - run: run
