name: Testing github actions 
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: canary
      - run: |
          curl -fsSL https://bun.sh/install | bash
           echo "::add-path::$HOME/.bun/bin"
      - name: "Install dependencies"
        run: bun install
      - name: "Build"
        run: npm run build
      - name: "Test dev mode"
        uses: ./
        with:
          dev: ${{ github.event.inputs.LOCAL }}
      - run: run
      - run: $HOME/run/run/bin/cmd.ts
      - name: "Test published mode"
        uses: ./
        with:
          dev: false
      - run: run