name: Testing github actions 
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths: 
      - 'actions/vault/**'  
env:
  SRC: ${{github.workspace}}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
  VAULT_ADDR: ${{ secrets.VAULT_ADDR}}
jobs:
  vault:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v3
      - uses: ./actions/vault
        name: "install vault and login with inputs"
      


      